name: knockoff-game
version: '0.0.1'
main: gg.knockoff.game.knockoff
api-version: '1.21'
depend: [FastAsyncWorldEdit, Crystalized_Essentials]
softdepend: [floodgate]
commands:
  knockoff:
    description: "Commands for KnockOff"
    usage: "/knockoff [start/end/reload_config]"
    aliases: [ ]
    permission: knockoff.command.game
    permission-message: "[!] You don't have permission to run the command"